server:
  port: 8080

spring:
  datasource:
    username: xdnphb
    password: xdnphb_2015
    url: jdbc:mysql://192.168.2.210:3306/test_1?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: provider-service
  main:
      allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Dubbo 广播方式配置
dubbo:
  application:
    name: provider-service
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  scan:
    base-packages: com.xiao.impl
  protocol:
    name: dubbo
    port: 15511
