server:
  port: 8080
spring:
  application:
    name: interface

# 多数据源路由配置
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery?useUnicode=true
        username: root
        password: cd123456
      db01:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery_01?useUnicode=true
        username: root
        password: cd123456
      db02:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lottery_02?useUnicode=true
        username: root
        password: cd123456
#spring:
#  datasource:
#    username: root
#    password: cd123456
#    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
#    driver-class-name: com.mysql.jdbc.Driver
#  application:
#      name: provider-service
#  main:
#      allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  config-location:  classpath:/config/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Dubbo 广播方式配置
dubbo:
  application:
    name: provider-service
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  scan:
    base-packages: com.xiao.impl
  protocol:
    name: dubbo
    port: 15511
